version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
    overwrite: yes
file_exists_behavior: OVERWRITE    
permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: root
    group: root
hooks:
  ApplicationStop:
    - location: deploy/scripts/kill_process.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: deploy/scripts/run_process.sh
      timeout: 3600
      runas: root
